### ISSUE TITLE
Błąd odtwarzania muzyki w pygame 2.0.1 (SDL 2.0.14, Python 3.8.5)

### ISSUE THREAD

**Issue by abixadamj** [kodujwpythonie/koduj-w-pythonie#5]
Jeśli mamy najnowszą wersję Mu-Editor, możemy napotkać„ problem przy uruchomieniu kodu:
```
pygame 2.0.1 (SDL 2.0.14, Python 3.8.5)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/adasiek/.local/share/mu/mu_venv-38-20210512-082808/lib/python3.8/site-packages/pgzero/
__main__.py", line 3, in <module>
    main()
  File "/home/adasiek/.local/share/mu/mu_venv-38-20210512-082808/lib/python3.8/site-packages/pgzero/
runner.py", line 92, in main
    exec(code, mod.__dict__)
  File "koduj_w_pythonie.py", line 415, in <module>
    game = Game(background_active, rooms_in_game)
  File "koduj_w_pythonie.py", line 49, in __init__
    music.play("music-background.mp3")
  File "/home/adasiek/.local/share/mu/mu_venv-38-20210512-082808/lib/python3.8/site-packages/pgzero/
music.py", line 51, in play
    _play(name, -1)
  File "/home/adasiek/.local/share/mu/mu_venv-38-20210512-082808/lib/python3.8/site-packages/pgzero/
music.py", line 40, in _play
    _music.load(path)
pygame.error: Unrecognized audio format


---------- FINISHED ----------
exit code: 1 status: 0
```
![error_1](https://user-images.githubusercontent.com/5088643/117938997-ebf86680-b307-11eb-99e5-cca6b50d6d5a.png)
![error_2](https://user-images.githubusercontent.com/5088643/117939008-eef35700-b307-11eb-8da1-90d481fa3b2c.png)

To jest spowodowane faktem, że pygame od wersji 2 z powodów licencyjnych nie odtwarza plików mp3.
W starej wersji pygame 1.9.6 wszystko działa poprawnie.
![ok](https://user-images.githubusercontent.com/5088643/117940354-43e39d00-b309-11eb-8004-335cba1f80d3.png)

**Comment by abixadamj** [comment]
# Rozwiązanie problemu:

## Należy przekonwertować pliki **mp3** na format otwarty **ogg** i w kodzie gry zmienić nazwy plików.

![music-ok2](https://user-images.githubusercontent.com/5088643/117940586-81482a80-b309-11eb-8bdf-c51c46c1225f.png)

## Wówczas wszystko zaczyna działać poprawnie.

![music-ok1](https://user-images.githubusercontent.com/5088643/117940628-8e651980-b309-11eb-8cef-5c849df5a79b.png)

Dla wszystkich w repozytorium umieścimy odpowiednie wersje plików.

**Comment by abixadamj** [comment]
Pliki są dostępne w katalogu 
https://github.com/kodujwpythonie/koduj-w-pythonie/tree/master/music
Dodałem commit - https://github.com/kodujwpythonie/koduj-w-pythonie/commit/cd0f69e99ad29c0ac5a021a1cb2cf87fb7eb471c
